spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.5.50:3306/hobo-frame
    username: root
    password: shlefantest.com
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
